AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation to create a CodePipeline to test IAM Policies and Roles

# add needed outputs here
# Outputs:
#   LoadingDockS3Bucket:
#     Value: !GetAtt LoadingDockS3Bucket.Arn
#     Export:
#       Name: LoadingDockS3Bucket
Parameters:
  CurrentAccountId:
    Type: String
    Default: !Ref "AWS::AccountId"
  Repo:
    Type: String
    Description: Repository Name (not repo URL)
    Default: ''
  GitHubToken:
    NoEcho: 'true'
    Type: String
    Description: Secret. OAuthToken with access to Repo. Long string of characters
      and digits. Go to https://github.com/settings/tokens
    Default: ''
  GitHubUser:
    Type: String
    Description: GitHub UserName. This username must have access to the GitHubToken.
    Default: ''
  Branch:
    Type: String
    Description: The GitHub branch for the Pipeline to monitor.
    Default: master

Resources:
  DeveloperServiceRolePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: 'DeveloperServiceRoles'
      RoleArn:
        - !Sub 'arn:aws:iam::${CurrentAccountId}:role/AWS-CodePipeline-Service'
