AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation to create a CodePipeline to test IAM Policies and Roles

# add needed outputs here
# Outputs:
#   LoadingDockS3Bucket:
#     Value: !GetAtt LoadingDockS3Bucket.Arn
#     Export:
#       Name: LoadingDockS3Bucket
Parameters:
  Repo:
    Type: String
    Description: Repository Name (not repo URL)
    Default: 'ndlib/esu-iam'
  GitHubToken:
    NoEcho: 'true'
    Type: String
    Description: Secret. OAuthToken with access to Repo. Long string of characters
      and digits. Go to https://github.com/settings/tokens
    Default: 'd7d9141d5e22df93a00df01d4667b5327e8867b7'
  GitHubUser:
    Type: String
    Description: GitHub UserName. This username must have access to the GitHubToken.
    Default: 'ialford'
  Branch:
    Type: String
    Description: The GitHub branch for the Pipeline to monitor.
    Default: master

Resources:
  DeveloperServiceRolePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: 'DeveloperServiceRoles'
      ArtifactStore:
        Type: S3
        Location: cf-templates-momt4hoqvkiv-us-east-1
      RoleArn:
        Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/AWS-CodePipeline-Service'
      Stages:
      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: Source
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          # OutputArtifacts:
          # - Name:
          #     Ref: MyInputArtifacts
          Configuration:
            Owner:
              Ref: GitHubUser
            Repo:
              Ref: Repo
            Branch:
              Ref: Branch
            OAuthToken:
              Ref: GitHubToken
          RunOrder: 1
